### ISSUE TITLE
Status Title Bar does not work on GNOME Shell 3.30

### ISSUE THREAD

**Issue by trompette** [emerinohdz/status-title-bar#34]
Dear developper,

Recently, I upgraded my _Debian Testing_ and _GNOME Shell_ got upgraded in the process:

```
$ aptitude show gnome-shell
Paquet : gnome-shell                                    
Version : 3.30.0-3
```

Since then, _Status Title Bar_ does not work anymore:

![image](https://user-images.githubusercontent.com/181746/46730719-074ef100-cc89-11e8-920c-2d25e31e1c62.png)

What can I do to help?

Cheers!

**Comment by emerinohdz** [comment]
hi @trompette , I'll try to work on this during the weekend, I'll update my gnome shell version and see what the issue is

**Comment by emerinohdz** [comment]
Problem fixed in latest version, available in the master branch and once approved by GSE will also be available there

**Comment by trompette** [comment]
Thanks a lot for taking the time to work on this issue!

As soon as available on https://extensions.gnome.org/, I will test and close this issue.

**Comment by emerinohdz** [comment]
It's on GSE. Please validate if possible, to close the ticket. Thanks.

**Comment by trompette** [comment]
Hi @emerinohdz,

I installed the new version, but there is still an error:
![image](https://user-images.githubusercontent.com/181746/47989904-7122b500-e0e6-11e8-957d-27ce467d0cd8.png)

Do you need more info?

Cheers!

**Comment by emerinohdz** [comment]
Hi, can you please make sure you installed the right version? Try
installing on a fresh GS (create a new test user if possible).

Thanks.

**Comment by emerinohdz** [comment]
I'll take a look later today, I'm using the ñateest version and haven't had any issues, but I'll try with a fresh installation of GS.

**Comment by trompette** [comment]
Hi @emerinohdz,

The extension is now working like a charm!

![image](https://user-images.githubusercontent.com/181746/48089500-f13f3c80-e204-11e8-8538-1b156ae5ed2a.png)

I guess GS was in a weird transient state, and it looks like everything is now in order after I rebooted. :man_shrugging: 

Thanks for the fix!

**Comment by emerinohdz** [comment]
@trompette thanks for confirming, GS does that sometimes 😃
